version: "3"

services:
  mongo_deniska:
    container_name: mongo_deniska
    image: mongo:latest
    restart: always
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
      - ./mongodb_logs:/var/log/mongodb
    ports:
      - 27020:27017

  deniska_helper_bot:
    container_name: deniska_helper_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo_deniska

  mongo_express_deniska:
    container_name: mongo-express-deniska
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo_deniska:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-username}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo_deniska
