available_text_models: ["gpt-4o-mini", "gpt-4o", "o1-mini"]
available_premium_models: ["o1", "o3-mini"]
reasoning_models: ["o1-mini", "o1", "o3-mini"]
info:

  gpt-4o-mini:
    type: chat_completion
    name: gpt-4o-mini
    description: gpt-4o-mini is the fastest and cheapest, but still very smart model.

    price_per_1000_input_tokens: 0.000150
    price_per_1000_output_tokens: 0.000600

    scores:
      smart: 3
      fast: 5
      cheap: 5

  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is the <b>best balance</b> speed, smart, cheap.

    price_per_1000_input_tokens: 0.00250
    price_per_1000_output_tokens: 0.01000

    scores:
      smart: 4
      fast: 4
      cheap: 3

  o1-mini:
    type: chat_completion
    name: o1-mini
    description: o1-mini is <b>expensive and slow</b>, but the smartest model

    price_per_1000_input_tokens: 0.00110
    price_per_1000_output_tokens: 0.00440

    scores:
      smart: 4
      fast: 3
      cheap: 1

  o3-mini:
    type: chat_completion
    name: o3-mini
    description: o3-mini is <b>expensive</b>, but the smartest model

    price_per_1000_input_tokens: 0.00110
    price_per_1000_output_tokens: 0.00440

    scores:
      smart: 4
      fast: 3
      cheap: 1

  o1:
    type: chat_completion
    name: o1
    description: o1 is <b>extremely expensive</b>

    price_per_1000_input_tokens: 0.0150
    price_per_1000_output_tokens: 0.0600

    scores:
      smart: 5
      fast: 1
      cheap: 0

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
