available_text_models: ["gpt-4.1-nano", "gpt-4.1-mini", "o3-mini"]
available_premium_models: ["o1", , "gpt-4.1"]
reasoning_models: ["o1-mini", "o1", "o3-mini"]
info:
  o3-mini:
    type: chat_completion
    name: o3-mini
    description: o3-mini is <b>expensive</b>, but the smartest model

    price_per_1000_input_tokens: 0.00110
    price_per_1000_output_tokens: 0.00440

    scores:
      smart: 4
      fast: 4
      cheap: 2

  o1:
    type: chat_completion
    name: o1
    description: o1 is <b>extremely expensive</b>

    price_per_1000_input_tokens: 0.0150
    price_per_1000_output_tokens: 0.0600

    scores:
      smart: 5
      fast: 1
      cheap: 0

  gpt-4.1-nano:
    type: chat_completion
    name: GPT-4.1 Nano
    description: GPT-4.1 Nano is a fast and affordable model with good capabilities.

    price_per_1000_input_tokens: 0.000200
    price_per_1000_output_tokens: 0.000800

    scores:
      smart: 2
      fast: 5
      cheap: 5

  gpt-4.1-mini:
    type: chat_completion
    name: GPT-4.1 Mini
    description: GPT-4.1 Mini offers enhanced capabilities while remaining cost-effective.

    price_per_1000_input_tokens: 0.000300
    price_per_1000_output_tokens: 0.001200

    scores:
      smart: 3
      fast: 4
      cheap: 4

  gpt-4.1:
    type: chat_completion
    name: GPT-4.1
    description: GPT-4.1 is a <b>premium model</b> with superior performance.

    price_per_1000_input_tokens: 0.0100
    price_per_1000_output_tokens: 0.0400

    scores:
      smart: 4
      fast: 4
      cheap: 2

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
