available_text_models: ["gpt-5-nano", "gpt-5-mini"]
available_premium_models: ["gpt-5", "gpt-5-mini-thinking"]
reasoning_models: ["gpt-5-nano", "gpt-5-mini", "gpt-5", "gpt-5-mini-thinking"]
info:

  gpt-5:
    type: chat_completion
    name: GPT-5
    description: GPT-5 is <b>extremely expensive</b>

    price_per_1000_input_tokens: 0.0150
    price_per_1000_output_tokens: 0.0600

    scores:
      smart: 5
      fast: 1
      cheap: 0

  gpt-5-nano:
    type: chat_completion
    name: GPT-5 Nano
    description: GPT-5 Nano is a fast and affordable model with good capabilities.

    price_per_1000_input_tokens: 0.000200
    price_per_1000_output_tokens: 0.000800

    scores:
      smart: 2
      fast: 5
      cheap: 5

  gpt-5-mini:
    type: chat_completion
    name: GPT-5 Mini
    description: GPT-5 Mini offers enhanced capabilities while remaining cost-effective.

    price_per_1000_input_tokens: 0.000300
    price_per_1000_output_tokens: 0.001200

    scores:
      smart: 3
      fast: 4
      cheap: 4

  gpt-5-mini-thinking:
    type: chat_completion
    name: GPT-5 Mini Thinking
    description: GPT-5 Mini offers enhanced capabilities while remaining cost-effective.

    price_per_1000_input_tokens: 0.000300
    price_per_1000_output_tokens: 0.001200

    scores:
      smart: 5
      fast: 0
      cheap: 0

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
